library(terra)

# Set directory structure
relPath <- "D:/Research/DroughtForecasts/"
outputPath <- "Outputs/"
rangeSizePath <- "/SuitabilityMaps/"
mapPath <- "Data/DiversityMaps/"
summaryPath <- "Data/DiversityMaps/Summary/"
figPath <- "Manuscript/Figures/"
countryPath <- "Data/CountriesOutline/world-administrative-boundaries.shp"

# List species
speciesDirs <- list.dirs(paste0(relPath, outputPath), recursive = F)

# List suitability maps
suitFiles <- list.files(paste0(speciesDirs[1], rangeSizePath), pattern = "tif$", recursive = T)

# Create diversity maps
for (i in 1:length(suitFiles)) {
  print(i)
  tmp <- lapply(paste0(speciesDirs, rangeSizePath, suitFiles[i]), rast)
  tmp <- sprc(tmp)
  stacked <- mosaic(tmp, fun = "sum")
  writeRaster(stacked, paste0(relPath, mapPath, suitFiles[i]), overwrite = T)
  png(filename = sub(".tif", ".png", paste0(relPath, mapPath, suitFiles[i]), fixed = T), width = 10, height = 10, units = "in", res = 320)
  plot(stacked, range = c(0, 85))
  dev.off()
}

# Create current summary maps
ase_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Current/"), "^ase_.*tif$", full.names = T), rast)), na.rm = T)
writeRaster(ase_mean, paste0(relPath, summaryPath, "ase_current_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ase_current_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ase_mean, range = c(0, 85))
dev.off()
ae_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Current/"), "^ae_.*tif$", full.names = T), rast)), na.rm = T)
writeRaster(ae_mean, paste0(relPath, summaryPath, "ae_current_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ae_current_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ae_mean, range = c(0, 85))
dev.off()
all_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Current/"), "^a.*tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_mean, paste0(relPath, summaryPath, "all_current_mean.tif"))
png(filename = paste0(relPath, summaryPath, "all_current_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_mean, range = c(0, 85))
dev.off()
all_sd <- stdev(rast(lapply(list.files(paste0(relPath, mapPath, "Current/"), "^a.*tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_sd, paste0(relPath, summaryPath, "all_current_sd.tif"))
png(filename = paste0(relPath, summaryPath, "all_current_sd.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_sd, range = c(0, 35))
dev.off()
all_cv <- all_sd / all_mean
writeRaster(all_cv, paste0(relPath, summaryPath, "all_current_cv.tif"))
png(filename = paste0(relPath, summaryPath, "all_current_cv.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_cv, range = c(0, 5))
dev.off()

# Create future summary maps for SSP126
a_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a_.*_SSP126.tif$", full.names = T), rast)), na.rm = T)
writeRaster(a_mean, paste0(relPath, summaryPath, "a_SSP126_mean.tif"))
png(filename = paste0(relPath, summaryPath, "a_SSP126_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(a_mean, range = c(0, 85))
dev.off()
as_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^as_.*_SSP126.tif$", full.names = T), rast)), na.rm = T)
writeRaster(as_mean, paste0(relPath, summaryPath, "as_SSP126_mean.tif"))
png(filename = paste0(relPath, summaryPath, "as_SSP126_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(as_mean, range = c(0, 85))
dev.off()
ase_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^ase_.*_SSP126.tif$", full.names = T), rast)), na.rm = T)
writeRaster(ase_mean, paste0(relPath, summaryPath, "ase_SSP126_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ase_SSP126_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ase_mean, range = c(0, 85))
dev.off()
ae_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^ae_.*_SSP126.tif$", full.names = T), rast)), na.rm = T)
writeRaster(ae_mean, paste0(relPath, summaryPath, "ae_SSP126_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ae_SSP126_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ae_mean, range = c(0, 85))
dev.off()
all_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a.*_SSP126.tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_mean, paste0(relPath, summaryPath, "all_SSP126_mean.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP126_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_mean, range = c(0, 85))
dev.off()
all_sd <- stdev(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a.*_SSP126.tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_sd, paste0(relPath, summaryPath, "all_SSP126_sd.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP126_sd.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_sd, range = c(0, 35))
dev.off()
all_cv <- all_sd / all_mean
writeRaster(all_cv, paste0(relPath, summaryPath, "all_SSP126_cv.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP126_cv.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_cv, range = c(0, 5))
dev.off()

# Create future summary maps for SSP370
a_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a_.*_SSP370.tif$", full.names = T), rast)), na.rm = T)
writeRaster(a_mean, paste0(relPath, summaryPath, "a_SSP370_mean.tif"))
png(filename = paste0(relPath, summaryPath, "a_SSP370_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(a_mean, range = c(0, 85))
dev.off()
as_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^as_.*_SSP370.tif$", full.names = T), rast)), na.rm = T)
writeRaster(as_mean, paste0(relPath, summaryPath, "as_SSP370_mean.tif"))
png(filename = paste0(relPath, summaryPath, "as_SSP370_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(as_mean, range = c(0, 85))
dev.off()
ase_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^ase_.*_SSP370.tif$", full.names = T), rast)), na.rm = T)
writeRaster(ase_mean, paste0(relPath, summaryPath, "ase_SSP370_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ase_SSP370_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ase_mean, range = c(0, 85))
dev.off()
ae_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^ae_.*_SSP370.tif$", full.names = T), rast)), na.rm = T)
writeRaster(ae_mean, paste0(relPath, summaryPath, "ae_SSP370_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ae_SSP370_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ae_mean, range = c(0, 85))
dev.off()
all_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a.*_SSP370.tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_mean, paste0(relPath, summaryPath, "all_SSP370_mean.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP370_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_mean, range = c(0, 85))
dev.off()
all_sd <- stdev(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a.*_SSP370.tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_sd, paste0(relPath, summaryPath, "all_SSP370_sd.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP370_sd.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_sd, range = c(0, 35))
dev.off()
all_cv <- all_sd / all_mean
writeRaster(all_cv, paste0(relPath, summaryPath, "all_SSP370_cv.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP370_cv.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_cv, range = c(0, 5))
dev.off()

# Create future summary maps for SSP585
a_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a_.*_SSP585.tif$", full.names = T), rast)), na.rm = T)
writeRaster(a_mean, paste0(relPath, summaryPath, "a_SSP585_mean.tif"))
png(filename = paste0(relPath, summaryPath, "a_SSP585_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(a_mean, range = c(0, 85))
dev.off()
as_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^as_.*_SSP585.tif$", full.names = T), rast)), na.rm = T)
writeRaster(as_mean, paste0(relPath, summaryPath, "as_SSP585_mean.tif"))
png(filename = paste0(relPath, summaryPath, "as_SSP585_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(as_mean, range = c(0, 85))
dev.off()
ase_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^ase_.*_SSP585.tif$", full.names = T), rast)), na.rm = T)
writeRaster(ase_mean, paste0(relPath, summaryPath, "ase_SSP585_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ase_SSP585_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ase_mean, range = c(0, 85))
dev.off()
ae_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^ae_.*_SSP585.tif$", full.names = T), rast)), na.rm = T)
writeRaster(ae_mean, paste0(relPath, summaryPath, "ae_SSP585_mean.tif"))
png(filename = paste0(relPath, summaryPath, "ae_SSP585_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(ae_mean, range = c(0, 85))
dev.off()
all_mean <- mean(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a.*_SSP585.tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_mean, paste0(relPath, summaryPath, "all_SSP585_mean.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP585_mean.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_mean, range = c(0, 85))
dev.off()
all_sd <- stdev(rast(lapply(list.files(paste0(relPath, mapPath, "Future/"), "^a.*_SSP585.tif$", full.names = T), rast)), na.rm = T)
writeRaster(all_sd, paste0(relPath, summaryPath, "all_SSP585_sd.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP585_sd.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_sd, range = c(0, 35))
dev.off()
all_cv <- all_sd / all_mean
writeRaster(all_cv, paste0(relPath, summaryPath, "all_SSP585_cv.tif"))
png(filename = paste0(relPath, summaryPath, "all_SSP585_cv.png"), width = 10, height = 10, units = "in", res = 320)
plot(all_cv, range = c(0, 5))
dev.off()

# Create change maps for SSP126
setwd(paste0(relPath, summaryPath))
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
tmp <- rast("a_SSP126_mean.tif") - rast("a_current_mean.tif")
writeRaster(tmp, "a_SSP126_changeAbs.tif")
png(filename = "a_SSP126_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-35, 35))
dev.off()
tmp <- rast("a_SSP126_mean.tif") / rast("a_current_mean.tif")
writeRaster(tmp, "a_SSP126_changeRel.tif")
png(filename = "a_SSP126_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("as_SSP126_mean.tif") - rast("as_current_mean.tif")
writeRaster(tmp, "as_SSP126_changeAbs.tif")
png(filename = "as_SSP126_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-35, 35))
dev.off()
tmp <- rast("as_SSP126_mean.tif") / rast("as_current_mean.tif")
writeRaster(tmp, "as_SSP126_changeRel.tif")
png(filename = "as_SSP126_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("ae_SSP126_mean.tif") - rast("ae_current_mean.tif")
writeRaster(tmp, "ae_SSP126_changeAbs.tif")
png(filename = "ae_SSP126_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-70, 70))
dev.off()
tmp <- rast("ae_SSP126_mean.tif") / rast("ae_current_mean.tif")
writeRaster(tmp, "ae_SSP126_changeRel.tif")
png(filename = "ae_SSP126_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("ase_SSP126_mean.tif") - rast("ase_current_mean.tif")
writeRaster(tmp, "ase_SSP126_changeAbs.tif")
png(filename = "ase_SSP126_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-70, 70))
dev.off()
tmp <- rast("ase_SSP126_mean.tif") / rast("ase_current_mean.tif")
writeRaster(tmp, "ase_SSP126_changeRel.tif")
png(filename = "ase_SSP126_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()

# Create change maps for SSP370
tmp <- rast("a_SSP370_mean.tif") - rast("a_current_mean.tif")
writeRaster(tmp, "a_SSP370_changeAbs.tif")
png(filename = "a_SSP370_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-35, 35))
dev.off()
tmp <- rast("a_SSP370_mean.tif") / rast("a_current_mean.tif")
writeRaster(tmp, "a_SSP370_changeRel.tif")
png(filename = "a_SSP370_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("as_SSP370_mean.tif") - rast("as_current_mean.tif")
writeRaster(tmp, "as_SSP370_changeAbs.tif")
png(filename = "as_SSP370_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-35, 35))
dev.off()
tmp <- rast("as_SSP370_mean.tif") / rast("as_current_mean.tif")
writeRaster(tmp, "as_SSP370_changeRel.tif")
png(filename = "as_SSP370_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("ae_SSP370_mean.tif") - rast("ae_current_mean.tif")
writeRaster(tmp, "ae_SSP370_changeAbs.tif")
png(filename = "ae_SSP370_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-75, 75))
dev.off()
tmp <- rast("ae_SSP370_mean.tif") / rast("ae_current_mean.tif")
writeRaster(tmp, "ae_SSP370_changeRel.tif")
png(filename = "ae_SSP370_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("ase_SSP370_mean.tif") - rast("ase_current_mean.tif")
writeRaster(tmp, "ase_SSP370_changeAbs.tif")
png(filename = "ase_SSP370_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-75, 75))
dev.off()
tmp <- rast("ase_SSP370_mean.tif") / rast("ase_current_mean.tif")
writeRaster(tmp, "ase_SSP370_changeRel.tif")
png(filename = "ase_SSP370_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()

# Create change maps for SSP585
tmp <- rast("a_SSP585_mean.tif") - rast("a_current_mean.tif")
writeRaster(tmp, "a_SSP585_changeAbs.tif")
png(filename = "a_SSP585_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-35, 35))
dev.off()
tmp <- rast("a_SSP585_mean.tif") / rast("a_current_mean.tif")
writeRaster(tmp, "a_SSP585_changeRel.tif")
png(filename = "a_SSP585_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("as_SSP585_mean.tif") - rast("as_current_mean.tif")
writeRaster(tmp, "as_SSP585_changeAbs.tif")
png(filename = "as_SSP585_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-35, 35))
dev.off()
tmp <- rast("as_SSP585_mean.tif") / rast("as_current_mean.tif")
writeRaster(tmp, "as_SSP585_changeRel.tif")
png(filename = "as_SSP585_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("ae_SSP585_mean.tif") - rast("ae_current_mean.tif")
writeRaster(tmp, "ae_SSP585_changeAbs.tif")
png(filename = "ae_SSP585_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-75, 75))
dev.off()
tmp <- rast("ae_SSP585_mean.tif") / rast("ae_current_mean.tif")
writeRaster(tmp, "ae_SSP585_changeRel.tif")
png(filename = "ae_SSP585_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()
tmp <- rast("ase_SSP585_mean.tif") - rast("ase_current_mean.tif")
writeRaster(tmp, "ase_SSP585_changeAbs.tif")
png(filename = "ase_SSP585_changeAbs.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(-75, 75))
dev.off()
tmp <- rast("ase_SSP585_mean.tif") / rast("ase_current_mean.tif")
writeRaster(tmp, "ase_SSP585_changeRel.tif")
png(filename = "ase_SSP585_changeRel.png", width = 10, height = 10, units = "in", res = 320)
plot(tmp, range = c(0, 2))
dev.off()

# Create manuscript figures
richnessA <- rast(paste0(relPath, mapPath, "Current/a_current_current.tif"))
richnessB <- rast(paste0(relPath, mapPath, "Current/as_current_current.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_current_mean.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_current_mean.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
png(paste0(relPath, figPath, "Fig3.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()

richnessA <- rast(paste0(relPath, mapPath, "Current/ae_GFDL-ESM4_current.tif"))
richnessB <- rast(paste0(relPath, mapPath, "Current/ae_MPI-ESM1-2-HR_current.tif"))
richnessC <- rast(paste0(relPath, mapPath, "Current/ae_UKESM1-0-LL_current.tif"))
richnessD <- rast(paste0(relPath, mapPath, "Current/ase_GFDL-ESM4_current.tif"))
richnessE <- rast(paste0(relPath, mapPath, "Current/ase_MPI-ESM1-2-HR_current.tif"))
richnessF <- rast(paste0(relPath, mapPath, "Current/ase_UKESM1-0-LL_current.tif"))
png(paste0(relPath, figPath, "ExtendedDataFig1.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 3), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 1.5))
plotA <- plot(richnessA, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0, line = -1)
mtext("GFDL-ESM4 (AD)", side = 3, cex = 0.75, line = -2)
plotB <- plot(richnessB, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0, line = -1)
mtext("MPI-ESM1-2-HR (AD)", side = 3, cex = 0.75, line = -2)
plotC <- plot(richnessC, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0, line = -1)
mtext("UKESM1-0-LL (AD)", side = 3, cex = 0.75, line = -2)
plotD <- plot(richnessD, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0, line = -1)
mtext("GFDL-ESM4 (ASD)", side = 3, cex = 0.75, line = -2)
plotE <- plot(richnessE, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("e")), side = 3, adj = 0, line = -1)
mtext("MPI-ESM1-2-HR (ASD)", side = 3, cex = 0.75, line = -2)
plotF <- plot(richnessF, box = F, axes = F, range = c(0, 80), plg = list(title = "Species", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("f")), side = 3, adj = 0, line = -1)
mtext("UKESM1-0-LL (ASD)", side = 3, cex = 0.75, line = -2)
dev.off()

richnessA <- rast(paste0(relPath, summaryPath, "a_SSP370_changeRel.tif"))
richnessB <- rast(paste0(relPath, summaryPath, "as_SSP370_changeRel.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_SSP370_changeRel.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_SSP370_changeRel.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
png(paste0(relPath, figPath, "Fig4.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()

richnessA <- rast(paste0(relPath, summaryPath, "a_SSP126_changeRel.tif"))
richnessB <- rast(paste0(relPath, summaryPath, "as_SSP126_changeRel.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_SSP126_changeRel.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_SSP126_changeRel.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
png(paste0(relPath, figPath, "ExtendedDataFig3.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()

richnessA <- rast(paste0(relPath, summaryPath, "a_SSP585_changeRel.tif"))
richnessB <- rast(paste0(relPath, summaryPath, "as_SSP585_changeRel.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_SSP585_changeRel.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_SSP585_changeRel.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
png(paste0(relPath, figPath, "ExtendedDataFig4.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(0, 2), plg = list(title = "Richness change\n(relative)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()

richnessA <- rast(paste0(relPath, summaryPath, "a_SSP126_changeAbs.tif"))
richnessB <- rast(paste0(relPath, summaryPath, "as_SSP126_changeAbs.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_SSP126_changeAbs.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_SSP126_changeAbs.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
png(paste0(relPath, figPath, "ExtendedDataFig5.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(-15, 15), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(-15, 15), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(-55, 55), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(-55, 55), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()

richnessA <- rast(paste0(relPath, summaryPath, "a_SSP370_changeAbs.tif"))
richnessB <- rast(paste0(relPath, summaryPath, "as_SSP370_changeAbs.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_SSP370_changeAbs.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_SSP370_changeAbs.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
png(paste0(relPath, figPath, "ExtendedDataFig6.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(-30, 30), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(-30, 30), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(-65, 65), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(-65, 65), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()

richnessA <- rast(paste0(relPath, summaryPath, "a_SSP585_changeAbs.tif"))
richnessB <- rast(paste0(relPath, summaryPath, "as_SSP585_changeAbs.tif"))
richnessC <- rast(paste0(relPath, summaryPath, "ae_SSP585_changeAbs.tif"))
richnessD <- rast(paste0(relPath, summaryPath, "ase_SSP585_changeAbs.tif"))
countries <- vect(paste0(relPath, countryPath))
countries <- project(countries, richnessA)
options(terra.pal = hcl.colors(100, palette = "Red-Green"))
png(paste0(relPath, figPath, "ExtendedDataFig7.png"), units = "mm", width = 180, height = 180, res = 300)
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1), oma = c(0, 0, 0, 0))
plotA <- plot(richnessA, box = F, axes = F, range = c(-35, 35), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("a")), side = 3, adj = 0)
mtext("A", side = 3, cex = 0.75, line = -0.25)
plotB <- plot(richnessB, box = F, axes = F, range = c(-35, 35), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("b")), side = 3, adj = 0)
mtext("AS", side = 3, cex = 0.75, line = -0.25)
plotC <- plot(richnessC, box = F, axes = F, range = c(-70, 70), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("c")), side = 3, adj = 0)
mtext("AD", side = 3, cex = 0.75, line = -0.25)
plotD <- plot(richnessD, box = F, axes = F, range = c(-70, 70), plg = list(title = "Richness change\n(species)", title.cex = 0.5, cex = 0.5, size = c(0.75, 0.5)), mar = c(1.5, 1.5, 1.5, 1.5), buffer = F, cex.main = 0.75)
sbar(1000000, "bottomleft", type = "bar", labels = c("", "1,000 km", ""), cex = 0.5)
plot(countries, add = T)
mtext(expression(bold("d")), side = 3, adj = 0)
mtext("ASD", side = 3, cex = 0.75, line = -0.25)
dev.off()


par(mfrow = c(1, 1))